context:
  version: "32.0"
  major: 6

package:
  name: protobuf-bazel-rules
  version: ${{ version }}

source:
  url: https://github.com/protocolbuffers/protobuf/releases/download/v${{ version }}/protobuf-${{ version }}.tar.gz
  sha256: 9dfdf08129f025a6c5802613b8ee1395044fecb71d38210ca59ecad283ef68bb

build:
  number: 0
  noarch: generic

requirements:
  run_constraints:
    - protobuf ${{ major }}.${{ version }}.*
    - libprotobuf ${{ major }}.${{ version }}.*

tests:
  - package_contents:
      files:
        - share/bazel/protobuf/bazel/cc_proto_library.bzl

about:
  homepage: https://developers.google.com/protocol-buffers/
  repository: https://github.com/protocolbuffers/protobuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bazel rules for protobuf

extra:
  recipe-maintainers:
    - conda-forge/libprotobuf
